packages:
  - "apps/*"
  - "apps/agents/*"
  - "packages/*"

catalog:
  "@tailwindcss/postcss": "^4.1.11"
  "@types/node": "^20.19.9"
  "@types/react": "^19.2.8"
  "@types/react-dom": "^19.2.3"
  "@turbo/gen": "^2.6.1"
  "dotenv-cli": "^7.3.0"
  "eslint": "^9.32.0"
  "hono": "^4.11.3"
  "lucide-react": "^0.562.0"
  "next": "^16.1.1"
  "next-themes": "^0.4.6"
  "react": "19.2.3"
  "react-dom": "19.2.3"
  "sonner": "^2.0.7"
  "typescript": "^5.9.2"
  "tailwindcss": "^4.1.11"
  "postcss": "^8.4.35"
  "zod": "^3"
